### PR TITLE
document `cog debug dockerfile`

### PR DESCRIPTION
**Pull request by zeke**
This PR updates the getting started guide with a note about how to view the dockerfile generated by Cog. A better long-term home for this information would be Cog's CLI docs, but those don't exist yet. See https://github.com/replicate/cog/issues/433

Resolves https://github.com/replicate/cog/issues/265

### CODE REVIEW

**Comment by dashstander** [comment]
Looks good to me! And definitely nice to have until there are more comprehensive CLI docs.

**Review by dashstander — APPROVED** [review]
👍

**Comment by bfirsh** [comment]
I wonder whether this might be a distraction mid-getting-started-flow? Or maybe it's helpful to understand what's going on? ("Wow look at all this complicated stuff I didn't have to do")

**Comment by bfirsh** [comment]
Also this was intentionally under the `cog debug` namespace so we don't have to commit to maintaining it. (E.g. if we ever move off Dockerfiles.)

If we ever have some CLI documentation we should make it clear that there are no guarantees this will stick around.

**Comment by zeke** [comment]
I've heard enough people asking how to do this on GitHub, Discord, and IRL that I think it's worth documenting, even if it does go away.

**Pull request merged**
