### PR TITLE
Add ENV NVIDIA_DRIVER_CAPABILITIES=all to permit Video SDK transcoding, 3D rendering, and X11 OpenGL Display

### PR DESCRIPTION
**Pull request by nelsonjchen**
https://github.com/NVIDIA/nvidia-container-runtime/issues/112

I'm interested in capabilities beyond the default Nvidia base images of just compute and utility. I'm particularly interested in using the video encoding and decoding functionality and OpenGL in an X11 application.

### CODE REVIEW

**Comment by nelsonjchen** [comment]
Hmm works locally on my WSL2 machine but not on replicate.com itself. Will need to continue investigating.

**Comment by nelsonjchen** [comment]
https://replicate.com/p/jokv5fbbljv3mu64k4eyyyqjli

Nope, got it working after all. Pretty pleased :) . I would like to bring this up for re-consideration.

**Comment by nelsonjchen** [comment]
Could there be some consideration of this? It is not possible to set this at runtime and get the same results as the Nvidia parts of the runtime will mount more files into the container if it sees these environment variables set. That is not something possible when the container is already running.

**Comment by zeke** [comment]
Hi @nelsonjchen sorry your PR went unnoticed. This seems like a sensible change to me, but do you have a sense of whether this change might break anything?

Wold you be willing to update this PR with docs about the purpose of this env var in https://github.com/replicate/cog/blob/main/docs/environment.md ?

**Comment by nelsonjchen** [comment]
> Hi @nelsonjchen sorry your PR went unnoticed. This seems like a sensible change to me, but do you have a sense of whether this change might break anything?

My sense is that it does not, but I am also not a typical/normal/daily GPU user. However, I do defer to this comment by an Nvidia employee in the thread I linked on Nvidia's repo about this which was made about 3 years ago with a general approval for this kind of change:

https://github.com/NVIDIA/nvidia-container-runtime/issues/112#issuecomment-712312284

> Wold you be willing to update this PR with docs about the purpose of this env var in https://github.com/replicate/cog/blob/main/docs/environment.md ?

I don't know. It's not really configurable which is unprecedented. The environment variables there are usually customizable. I suppose I could add a section of "interesting" environmental variables that can't be configured but might be of interest.

**Comment by nelsonjchen** [comment]
@zeke Documented. Not sure if that's what you're looking for.

**Review by zeke — APPROVED** [review]
This change looks good to me, and the documentation is clear and helpful. 👍🏼 

That said, I would like to get a second opinion from folks who have more expertise on the matter and can speak to possible issues that could arise from enabling this.

cc @technillogue @mattt @joehoover @anotherjesse @daanelson

**Comment by zeke** [comment]
Hey @nelsonjchen sorry there hasn't been much attention on this.

I think it'd be much less risky to ship this as an option than a new default. 👍🏼

**Comment by zeke** [comment]
Hey @nelsonjchen sorry there hasn't been much attention on this.

I think it'd be much less risky to ship this as an option than a new default. 👍🏼

**Comment by nelsonjchen** [comment]
OK, I'll see what I can do to propose it as an option.

**Comment by technillogue** [comment]
I think I'm fine with this even without it being an option. Can you rebase on main please?

**Review by technillogue — APPROVED** [review]

**Comment by nelsonjchen** [comment]
Rebased on main.

**Pull request merged**
