### PR TITLE
Add check_python to make targets (#101)

### PR DESCRIPTION
**Pull request by amarjandu**
#101 

```
gh0st-4:cog amar$ pyenv local 3.7.8
gh0st-4:cog amar$ make check_python
Python 3.7.8

Use Python 3.8

make: *** [check_python] Error 1
gh0st-4:cog amar$ pyenv local 3.8.2
gh0st-4:cog amar$ make check_python
gh0st-4:cog amar$
```

### CODE REVIEW

**Review by zeke — COMMENTED** [review]
I just gave this a try locally and it works for me.

However, I'm not sure that this change is resolving #101. I'll defer to @bfirsh to chime in on that.

**Comment by zeke** [comment]
@amarjandu were you using `3.7` and encountering issues?

**Comment by amarjandu** [comment]
It seemed like the issue was requesting that python was pinned to a specific version. I could have interpreted the issue incorrectly. @bfirsh is #101 to pin the version of python that is used to development or that is within the `yaml` files?

@zeke I have not encountered issues with 3.7, but I only installed it so I could test this PR, I use the python/go version that was specified in `.github/workflows/ci.yaml`.

**Comment by zeke** [comment]
Yeah #101 is about requiring that the version is specified in `cog.yaml`. I've updated that issue for clarity. Sorry for the confusion there.

As far as I'm aware, the dev environment doesn't currently require a specific version of Python, so I'm not sure this PR is needed.

**Pull request closed without merging**
