### PR TITLE
Handle symlinks in uploaded models

### PR DESCRIPTION
**Pull request by andreasjansson**
Signed-off-by: andreasjansson <andreas@replicate.ai>

### CODE REVIEW

**Comment by bfirsh** [comment]
Do we want to follow symlinks? This is 1) could be a security issue and 2) does not produce consistent results on different machines. I feel like it should be a property of Cog that two directories that are the same on different machines should produce the same version.

For context, Docker and git don't follow symlinks in any way. tar and zip don't unless explicitly told to.

**Comment by bfirsh** [comment]
Test failures are real, too!

**Comment by bfirsh** [comment]
I suppose another way of thinking about this – it should probably behave like doing a Docker build, and Docker doesn't follow symlinks.

**Comment by andreasjansson** [comment]
@bfirsh The use case I had in mind is when you have some small symlinked test set that's shared between several models. But I agree that repeatability probably trumps that use case. I'll scrap this and print warnings when there are symlinks in the directory.

**Pull request closed without merging**
