### PR TITLE
fix invalid empty lists in cog.yaml

### LINKED ISSUE #368: Lists in cog.yaml should be allowed to be empty
This cog.yaml:

```yaml
build:
  run:
  # - commented out
```

Throws this error:

```
ⅹ There is a problem in your cog.yaml file.
ⅹ must be a list.
ⅹ
ⅹ To see what options you can use, take a look at the docs:
ⅹ https://github.com/replicate/cog/blob/main/docs/yaml.md
ⅹ
ⅹ You might also need to upgrade Cog, if this option was added in a
ⅹ later version of Cog.
```

This should just evaluate to an empty list, so people can comment things out. (Also the error is broken.)

### PR DESCRIPTION
**Pull request by pysqz**
resolves #368. pls review it, @bfirsh

### CODE REVIEW

**Comment by pysqz** [comment]
> resolves #368. pls review it, @bfirsh

**Comment by bfirsh** [comment]
Nice, thanks! Would you mind writing a test?

**Comment by ccxx0** [comment]
> > Nice, thanks! Would you mind writing a test?
> 
> sure, test `cog init` is enough?

@bfirsh @zeke

**Comment by mattt** [comment]
Hi @pysqz. Thanks so much for your contribution. I just merged https://github.com/replicate/cog/pull/1073, which specifies [an array for `type`](https://json-schema.org/understanding-json-schema/reference/type.html#type) instead of using `anyOf`.

**Pull request closed without merging**
