### PR TITLE
Increase timeout of flakey test to 1.5s

### PR DESCRIPTION
**Pull request by technillogue**
this PR attempts to debug why hypothesis tests are flaking

### CODE REVIEW

**Comment by dkhokhlov** [comment]
> hypothesis.errors.DeadlineExceeded: Test took 1004.39ms, which exceeds the deadline of 1000.00ms
need to bump deadline in CI profile?

**Comment by technillogue** [comment]
I think it's always the exit_in_predict case, did something make that actually slower in a way we should fix directly?

**Comment by yorickvP** [comment]
I ran it locally and it failed the deadline in some other tests. Re-running them seems to have no issues, though. I vote to increase the deadline to 1.5s and think about it again if this re-surfaces.

**Comment by yorickvP** [comment]
LGTM. Can you cherry pick out the fake commit?

**Pull request merged**
