### PR TITLE
Remove references to nascent AMQP API

### PR DESCRIPTION
**Pull request by bfirsh**
This is not true. It will be soon. But right now it is confusing.

Signed-off-by: Ben Firshman <ben@firshman.co.uk>

### CODE REVIEW

**Review by zeke — APPROVED** [review]
👍🏼

**Comment by bfirsh** [comment]
Screen Shot 2022-03-10 at 08 43 30

No fun allowed 😂

**Comment by bfirsh** [comment]
(I appreciate you making this searchable though, haha.)

**Comment by sirupsen** [comment]
hah yeah I was confused when talking to Andreas about this. Readme-Driven-Development makes a comeback

**Pull request merged**
