### PR TITLE
Refactor `Makefile`

### PR DESCRIPTION
**Pull request by mattt**
This PR implements some changes I needed to get a Homebrew formula working (see https://github.com/replicate/cog/issues/822), specifically:

- Defining constants for executables like `PYTHON`. When Homebrew installs Python 3, my understanding is that it links to `python3`, keeping the default `python` (2.7) executable accessible in the default `PATH`. Because Python 3 is a prerequisite for building from source, we need a way to override this when running `make`.
- Adding an `install` target. In this PR, it's configured to be overridden by conventional `PREFIX` / `BINDIR` constants. It also supports [staged installs](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) using a `DESTDIR` constant.

This PR includes some other changes to keep the rest of the `Makefile` more consistent:

- Adding an `uninstall` target, to keep symmetry with `install`.
- Defining and using constants for `GO` and other executables.
- Adding a new default `all` target that builds `cog` as a prerequisite.
- Adding `go clean` to the `clean` target.

Finally, I noticed a TODO comment from @bfirsh for the `test-integration` target:

> `TODO(bfirsh): use local copy of cog so we don't have to install globally`

With the new `cog` target, we can run integration tests against local executables without installing them by prepending `PWD` to `PATH`. (afbd925bdb2458291493dc6b939d37b9a7d018e5)

### CODE REVIEW

**Comment by bfirsh** [comment]
😍 thank you!

One thing, which I'm curious if you have opinions on: we were considering just using `script/` files, because we don't really use makefile as a makefile. (I think we build the Python wheel as an actual target, but it's somewhat tenuous).

Any opinions on makefiles full of phonies vs just having some scripts?

**Comment by zeke** [comment]
Nice! I pressed the "Approve and Run" button to kick off CI here.

I know Makefiles are a tried and true old-school hacker convention, but I'm generally more in favor of [scripts to rule them all](https://github.com/github/scripts-to-rule-them-all) because they're just easier to comprehend than Makefiles, with less arcane syntax and none of that phony business. But yeah.. is it worth making the change? I dunno.

Looks like CI is 🍏, but when I ran this locally I hit a snag on `make install`:

```
$ make install
install -m 0755 cog /usr/local/bin/cog
install: /usr/local/bin/cog: Permission denied
make: *** [install] Error 71
```

Maybe just a permissions thing that's unique to my setup? `make install` does work for me on the main branch:

```
$ make install            
go install -ldflags "-X github.com/replicate/cog/pkg/global.Version=v0.5.0+dev -X github.com/replicate/cog/pkg/global.BuildTime=2022-12-04T22:31:18-0800 -w" cmd/cog/cog.go

$ cog --version
cog version v0.5.0+dev (built 2022-12-04T22:31:18-0800)

$ go version
go version go1.19.1 darwin/arm64
```

**Review by nickstenning — APPROVED** [review]
Perhaps let's add a `make install-dev` which does the `go install` this was previously doing? That would address @zeke's comment, I think.

Otherwise, LGTM.

**Comment by zeke** [comment]
> But before you do that, could you try running `make install INSTALL=cp` to check that the `install` command isn't the culprit?

```
~/git/replicate/cog pr/823
$ make install INSTALL=cp
CGO_ENABLED=0 go build -ldflags "-X github.com/replicate/cog/pkg/global.Version=v0.5.0+dev -X github.com/replicate/cog/pkg/global.BuildTime=2022-12-05T12:02:57-0800 -w" -o cog cmd/cog/cog.go
cp cog /usr/local/bin/cog
cp: /usr/local/bin/cog: Permission denied
make: *** [install] Error 1
```

> Running `sudo make install` should do the trick.

```
$ sudo make install
Password:
fatal: unsafe repository ('/Users/z/git/replicate/cog' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /Users/z/git/replicate/cog
install -m 0755 cog /usr/local/bin/cog
```

**Review by zeke — APPROVED** [review]
That worked!

I'm all for shipping this. If it has any rough edges, or if we decide we want to "add a `make install-dev` which does the `go install` this was previously doing" as @nickstenning suggested, we can iterate.

**Comment by zeke** [comment]
@allcontributors please add @mattt for code, docs, infra

**Pull request merged**
