### PR TITLE
add a Pull Request template

### PR DESCRIPTION
**Pull request by zeke**
This PR adds a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to help remind contributors to describe the changes they're making, and include tests and documentation as appropriate.

This will show up as the default text in the textarea when opening a PR. Authors can keep it and fill it out, or delete it and start fresh.

### CODE REVIEW

**Comment by mattt** [comment]
@zeke I haven't found our volume or quality of PRs to cause any problems so far. PR templates can be nice for enforcing rules and process, but I'm not sure we need something like that right now.

**Comment by zeke** [comment]
I disagree. Every PR we land that adds a feature without accompanying docs becomes a liability.

I think we'll get better and more accurate docs if they are contributed by the authors of the features, at the time of implementation. Furthermore, writing docs gives authors an extra opportunity to consider the shape of the feature they're proposing, test it, and evaluate whether it actually works and makes sense.

**Comment by erbridge** [comment]
I agree with the sentiment of a pull request template, but I don't think this one has enough guidance or structure as to what to do with it. By my naive reading, the comment seems to apply to the check list, but in a way that doesn't make sense (am I supposed to write tests and docs that describe the pull request?).

**Comment by mattt** [comment]
I agree with @erbridge. I think a pull request template can be helpful, but I don't think this particular implementation would add much.

Happy to revisit this once we've identified a specific need for PR template, or have more consensus around what kind of process we want to have for this project.

**Pull request closed without merging**
