### PR TITLE
update pillow and tensorflow versions in getting started guide

### LINKED ISSUE #592: ImportError: cannot import name 'ParamSpec' from 'typing_extensions'
I got this issue when I tried to follow [this tutorial](https://github.com/replicate/cog/blob/main/docs/getting-started.md). A minimal reproducible `cog.yaml`
```yaml
build:
  python_version: "3.8"
  python_packages:
    - pillow==8.3.1
    - tensorflow==2.5.0
```

Run `cog build`, we'll get this
```
(ins)luan@tuf:~/research/cog-quickstart$ cog build                                                                                                            
Building Docker image from environment in cog.yaml as cog-cog-quickstart...                                                                                   
[+] Building 4.1s (14/14) FINISHED                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                     0.0s 
 => => transferring dockerfile: 622B                                                                                                                     0.0s 
 => [internal] load .dockerignore                                                                                                                        0.0s                                 
 => => transferring context: 2B                                                                                                                          0.0s                                 
 => resolve image config for docker.io/docker/dockerfile:1.2                                                                                             1.2s                                 
 => CACHED docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab1ba6b2fe6cbdf49fd92b95912df1cf7d313c3e2230a333fdbcc                        0.0s                                 
 => [internal] load metadata for docker.io/library/python:3.8                                                                                            1.2s                                 
 => [stage-0 1/6] FROM docker.io/library/python:3.8@sha256:f732d55571549b427e12edb89d0951372e7b73c67f717ad0645bb0cda19fc05e                              0.0s 
 => [internal] load build context                                                                                                                        0.4s 
 => => transferring context: 105.91MB                                                                                                                    0.4s 
 => CACHED [stage-0 2/6] COPY .cog/tmp/build2578025161/cog-0.0.1.dev-py3-none-any.whl /tmp/cog-0.0.1.dev-py3-none-any.whl                                0.0s 
 => CACHED [stage-0 3/6] RUN --mount=type=cache,target=/root/.cache/pip pip install /tmp/cog-0.0.1.dev-py3-none-any.whl                                  0.0s 
 => CACHED [stage-0 4/6] RUN --mount=type=cache,target=/root/.cache/pip pip install   pillow==8.3.1 tensorflow==2.5.0                                    0.0s 
 => CACHED [stage-0 5/6] WORKDIR /src                                                                                                                    0.0s                                                                                 
 => [stage-0 6/6] COPY . /src                                                                                                                            0.6s                                                                                 
 => exporting to image                                                                                                                                   0.0s                                                                                 
 => => exporting layers                                                                                                                                  0.0s                                                                                 
 => => writing image sha256:f0def1a441798ec882f8e39c3d029283cec2d341724424cde7350e247664352d                                                             0.0s                                                                                 
 => => naming to docker.io/library/cog-cog-quickstart                                                                                                    0.0s                                                                                 
 => exporting cache                                                                                                                                      0.0s                                                                                 
 => => preparing build cache for export                                                                                                                  0.0s                                                                                 
Adding labels to image...                                  

Traceback (most recent call last):                         
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                           
    return _run_code(code, main_globals, None,                                                                         
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code                                                      
    exec(code, run_globals)                                
  File "/usr/local/lib/python3.8/site-packages/cog/command/openapi_schema.py", line 12, in <module>                                                                                                                                           
    from ..server.http import create_app                                                                               
  File "/usr/local/lib/python3.8/site-packages/cog/server/http.py", line 5, in <module>                                                                                                                                                       
    from fastapi import Body, FastAPI, HTTPException                                                                   
  File "/usr/local/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>                                                                                                                                                      
    from .applications import FastAPI as FastAPI                                                                       
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 4, in <module>                                                                                                                                                  
    from fastapi import routing                            
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 22, in <module>                                                                                                                                                      
    from fastapi.datastructures import Default, DefaultPlaceholder                                                     
  File "/usr/local/lib/python3.8/site-packages/fastapi/datastructures.py", line 3, in <module>                                                                                                                                                
    from starlette.datastructures import URL as URL  # noqa: F401                                                      
  File "/usr/local/lib/python3.8/site-packages/starlette/datastructures.py", line 8, in <module>                                                                                                                                              
    from starlette.concurrency import run_in_threadpool                                                                
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 10, in <module>                                                                                                                                                
    from typing_extensions import ParamSpec                                                                            
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/usr/local/lib/python3.8/site-packages/typing_extensions.py)                                                                                                            

ⅹ Failed to get type signature: exit status 1                       
```

### PR DESCRIPTION
**Pull request by phamquiluan**
Fixed #592

### CODE REVIEW

**Comment by bfirsh** [comment]
Nice, thanks! This is an intriguing problem. Do you know why this might be fixing this issue?

**Comment by phamquiluan** [comment]
@bfirsh 
It seems to me that the "dependency hell" is the root cause since `tensorflow==2.5.0` requires `typing-extensions~=3.7.4` and `starlette` requires `typing-extensions` as `Any` but it asks for `ParamSpec` which has appeared since v4.1.0 https://github.com/python/typing/blob/master/typing_extensions/CHANGELOG.md

We can take a look at the pipdeptree output

```
root@d765a69562bc:/src# pipdeptree                                                                                     
cog==0.0.1                                                                                                             
  - fastapi [required: >=0.6,<1, installed: 0.76.0]                                                                    
    - pydantic [required: >=1.6.2,<2.0.0,!=1.8.1,!=1.8,!=1.7.3,!=1.7.2,!=1.7.1,!=1.7, installed: 1.9.0]                                                                                                                                       
      - typing-extensions [required: >=3.7.4.3, installed: 3.7.4.3]                                                    
    - starlette [required: ==0.18.0, installed: 0.18.0]                                                                
      - anyio [required: >=3.0.0,<4, installed: 3.5.0]                                                                 
        - idna [required: >=2.8, installed: 3.3]                                                                       
        - sniffio [required: >=1.1, installed: 1.2.0]                                                                  
      - typing-extensions [required: Any, installed: 3.7.4.3]                                                          
  - pydantic [required: >=1,<2, installed: 1.9.0]                                                                      
    - typing-extensions [required: >=3.7.4.3, installed: 3.7.4.3]                                                      
  - PyYAML [required: Any, installed: 6.0]                                                                             
  - redis [required: >=4,<5, installed: 4.3.0]                                                                         
    - async-timeout [required: >=4.0.2, installed: 4.0.2]                                                              
    - deprecated [required: >=1.2.3, installed: 1.2.13]                                                                
      - wrapt [required: >=1.10,<2, installed: 1.12.1]                                                                 
    - packaging [required: >=20.4, installed: 21.3]                                                                    
      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.8]                                                        
  - requests [required: >=2,<3, installed: 2.27.1]                                                                     
    - certifi [required: >=2017.4.17, installed: 2021.10.8]                                                            
    - charset-normalizer [required: ~=2.0.0, installed: 2.0.12]                                                        
    - idna [required: >=2.5,<4, installed: 3.3]                                                                        
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.9]                                                            
  - typing-extensions [required: >=3.7.4, installed: 3.7.4.3]                                                          
  - uvicorn [required: >=0.12,<1, installed: 0.17.6]                                                                   
    - asgiref [required: >=3.4.0, installed: 3.5.1]                                                                    
    - click [required: >=7.0, installed: 8.1.3]                                                                        
    - h11 [required: >=0.8, installed: 0.13.0]                                                                         
httptools==0.4.0                                                                                                       
pipdeptree==2.2.1                                                                                                      
  - pip [required: >=6.0.0, installed: 22.0.4]                                                                         
python-dotenv==0.20.0                                                                                                  
tensorflow==2.5.0                                                                                                      
  - absl-py [required: ~=0.10, installed: 0.15.0]                                                                      
    - six [required: Any, installed: 1.15.0]                                                                           
  - astunparse [required: ~=1.6.3, installed: 1.6.3]                                                                   
    - six [required: >=1.6.1,<2.0, installed: 1.15.0]                                                                  
    - wheel [required: >=0.23.0,<1.0, installed: 0.37.1]                                                               
  - flatbuffers [required: ~=1.12.0, installed: 1.12]                                                                  
  - gast [required: ==0.4.0, installed: 0.4.0]                                                                         
  - google-pasta [required: ~=0.2, installed: 0.2.0]                                                                   
    - six [required: Any, installed: 1.15.0]                                                                           
  - grpcio [required: ~=1.34.0, installed: 1.34.1]                                                                     
    - six [required: >=1.5.2, installed: 1.15.0]                                                                       
  - h5py [required: ~=3.1.0, installed: 3.1.0]                                                                         
    - numpy [required: >=1.17.5, installed: 1.19.5]                                                                    
  - keras-nightly [required: ~=2.5.0.dev, installed: 2.5.0.dev2021032900]                                              
  - keras-preprocessing [required: ~=1.1.2, installed: 1.1.2]                                                          
    - numpy [required: >=1.9.1, installed: 1.19.5]                                                                     
    - six [required: >=1.9.0, installed: 1.15.0]                                                                       
  - numpy [required: ~=1.19.2, installed: 1.19.5]                                                                      
  - opt-einsum [required: ~=3.3.0, installed: 3.3.0]                                                                   
    - numpy [required: >=1.7, installed: 1.19.5]                                                                       
  - protobuf [required: >=3.9.2, installed: 3.20.1]                                                                    
  - six [required: ~=1.15.0, installed: 1.15.0]                                                                        
  - tensorboard [required: ~=2.5, installed: 2.9.0]                                                                    
    - absl-py [required: >=0.4, installed: 0.15.0]                                                                     
      - six [required: Any, installed: 1.15.0]                                                                         
    - google-auth [required: >=1.6.3,<3, installed: 2.6.6]                                                             
      - cachetools [required: >=2.0.0,<6.0, installed: 5.0.0]                                                          
      - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]                                                           
        - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]                                                          
      - rsa [required: >=3.1.4,<5, installed: 4.8]                                                                     
        - pyasn1 [required: >=0.1.3, installed: 0.4.8]                                                                 
      - six [required: >=1.9.0, installed: 1.15.0]                                                                     
    - google-auth-oauthlib [required: >=0.4.1,<0.5, installed: 0.4.6]                                                  
      - google-auth [required: >=1.0.0, installed: 2.6.6]                                                              
        - cachetools [required: >=2.0.0,<6.0, installed: 5.0.0]                                                        
        - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]                                                         
          - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]                                                        
        - rsa [required: >=3.1.4,<5, installed: 4.8]                                                                   
          - pyasn1 [required: >=0.1.3, installed: 0.4.8]                                                               
        - six [required: >=1.9.0, installed: 1.15.0]                                                                   
      - requests-oauthlib [required: >=0.7.0, installed: 1.3.1]                                                        
        - oauthlib [required: >=3.0.0, installed: 3.2.0]                                                               
        - requests [required: >=2.0.0, installed: 2.27.1]                                                              
          - certifi [required: >=2017.4.17, installed: 2021.10.8]                                                      
          - charset-normalizer [required: ~=2.0.0, installed: 2.0.12]                                                  
          - idna [required: >=2.5,<4, installed: 3.3]                                                                  
          - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.9]                                                      
    - grpcio [required: >=1.24.3, installed: 1.34.1]                                                                   
      - six [required: >=1.5.2, installed: 1.15.0]                                                                     
    - markdown [required: >=2.6.8, installed: 3.3.7]                                                                   
      - importlib-metadata [required: >=4.4, installed: 4.11.3]                                                        
        - zipp [required: >=0.5, installed: 3.8.0]                                                                     
    - numpy [required: >=1.12.0, installed: 1.19.5]                                                                    
    - protobuf [required: >=3.9.2, installed: 3.20.1]                                                                  
    - requests [required: >=2.21.0,<3, installed: 2.27.1]                                                              
      - certifi [required: >=2017.4.17, installed: 2021.10.8]                                                          
      - charset-normalizer [required: ~=2.0.0, installed: 2.0.12]                                                      
      - idna [required: >=2.5,<4, installed: 3.3]                                                                      
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.9]                                                          
    - setuptools [required: >=41.0.0, installed: 57.5.0]                                                               
    - tensorboard-data-server [required: >=0.6.0,<0.7.0, installed: 0.6.1]                                             
    - tensorboard-plugin-wit [required: >=1.6.0, installed: 1.8.1]                                                     
    - werkzeug [required: >=1.0.1, installed: 2.1.2]                                                                   
    - wheel [required: >=0.26, installed: 0.37.1]                                                                      
  - tensorflow-estimator [required: >=2.5.0rc0,<2.6.0, installed: 2.5.0]                                               
  - termcolor [required: ~=1.1.0, installed: 1.1.0]                                                                    
  - typing-extensions [required: ~=3.7.4, installed: 3.7.4.3]                                                          
  - wheel [required: ~=0.35, installed: 0.37.1]                                                                        
  - wrapt [required: ~=1.12.1, installed: 1.12.1]                                                                      
uvloop==0.16.0                                                                                                         
watchgod==0.8.2                                                                                                        
  - anyio [required: >=3.0.0,<4, installed: 3.5.0]                                                                     
    - idna [required: >=2.8, installed: 3.3]                                                                           
    - sniffio [required: >=1.1, installed: 1.2.0]                                                                      
websockets==10.3                                                                                                       
root@d765a69562bc:/src# 

```

**Comment by bfirsh** [comment]
Yikes. Thank you. This is another safeguard: https://github.com/replicate/cog/pull/598

I think the proper fix is vendoring a compatible version of `typing-extensions`: #409

**Comment by zeke** [comment]
@all-contributors please add @phamquiluan for bugs and docs

**Pull request merged**
