### PR TITLE
allow arbitrary input types for model inputs

### PR DESCRIPTION
**Pull request by jgershen**
This is especially useful for transformers, where you often want to generate multiple text completions with the same settings. With this change, you can now define cog models which take in lists of strings as parameters.

### CODE REVIEW

**Comment by jgershen** [comment]
Example of use at https://github.com/replicate/cog-flan-t5/pull/1

**Comment by jgershen** [comment]
this probably doesn't fix all the test errors; I need to fix some package versions in my local dev env

**Comment by bfirsh** [comment]
Whomp looks like more failures. :(

**Comment by zeke** [comment]
> you can now define cog models which take in lists of strings as parameters.

Nice. Would you mind also updating the docs around this?

**Comment by mattt** [comment]
Closing in favor of https://github.com/replicate/cog/pull/1311 and/or https://github.com/replicate/cog/pull/1313. See https://github.com/replicate/cog/pull/1292#issuecomment-1730714860.

**Pull request closed without merging**
